all: boat direction gap link mesh node star

boat:
	$(MAKE) -C Boat
direction:
	$(MAKE) -C Direction
gap:
	$(MAKE) -C Gap
link:
	$(MAKE) -C Link
mesh:
	$(MAKE) -C Mesh
node:
	$(MAKE) -C Node
star:
	$(MAKE) -C Star
telescope:
	$(MAKE) -C Telescope
