all: direction gap link mesh net node star

direction:
	$(MAKE) -C Direction
gap:
	$(MAKE) -C Gap
link:
	$(MAKE) -C Link
mesh:
	$(MAKE) -C Mesh
net:
	$(MAKE) -C Net
node:
	$(MAKE) -C Node
star:
	$(MAKE) -C Star
telescope:
	$(MAKE) -C Telescope
